<!-- <h2>Title</h2> -->

---
<h1> 
    National Income Dynamics Study-Coronavirus Rapid Mobile Survey (NIDS-CRAM)<br>
    Wave 1: February - April 2020<br><br>
    The Effect of COVID-19 on the Labour and Welfare of South Africans
</h1>

--- 


<h1> 
Part 2 - Rough Draft
</h1>

--- 


<h2>Group Members</h2>
Dino Anastasopoulos: 1900661 - Contributed towards the Demographics section. <br>
Brenton Budler: 1827655 - Contributed towards the Labour section. <br>
Philani Mpofu: 1848751 - Contributed towards the Welfare section. <br>

---

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Group-Members" data-toc-modified-id="Group-Members-1">Group Members</a></span></li><li><span><a href="#Imports" data-toc-modified-id="Imports-2">Imports</a></span></li><li><span><a href="#Read-data" data-toc-modified-id="Read-data-3">Read data</a></span></li><li><span><a href="#Model" data-toc-modified-id="Model-4">Model</a></span><ul class="toc-item"><li><span><a href="#Drop-all-nans" data-toc-modified-id="Drop-all-nans-4.1">Drop all nans</a></span></li><li><span><a href="#Now-this-is-the-dataframe-of-all-people-who-kept-their-jobs,-and-have-usable-data" data-toc-modified-id="Now-this-is-the-dataframe-of-all-people-who-kept-their-jobs,-and-have-usable-data-4.2">Now this is the dataframe of all people who kept their jobs, and have usable data</a></span></li><li><span><a href="#Calculate-and-store-salary-difference" data-toc-modified-id="Calculate-and-store-salary-difference-4.3">Calculate and store salary difference</a></span></li><li><span><a href="#Remove-outliers" data-toc-modified-id="Remove-outliers-4.4">Remove outliers</a></span></li><li><span><a href="#Determine-if-salary-changed-and-create-new-variable-for-this" data-toc-modified-id="Determine-if-salary-changed-and-create-new-variable-for-this-4.5">Determine if salary changed and create new variable for this</a></span></li></ul></li><li><span><a href="#Check-value-counts-of-salary-change" data-toc-modified-id="Check-value-counts-of-salary-change-5">Check value counts of salary change</a></span></li><li><span><a href="#Check-details-of-work-type" data-toc-modified-id="Check-details-of-work-type-6">Check details of work type</a></span><ul class="toc-item"><li><span><a href="#Remove-all-nonsensical-dara-(not-applicable-and-unknown)-and-jobs-with-too-few-occurences" data-toc-modified-id="Remove-all-nonsensical-dara-(not-applicable-and-unknown)-and-jobs-with-too-few-occurences-6.1">Remove all nonsensical dara (not applicable and unknown) and jobs with too few occurences</a></span></li></ul></li><li><span><a href="#Check-details-of-province" data-toc-modified-id="Check-details-of-province-7">Check details of province</a></span><ul class="toc-item"><li><span><a href="#Encode-some-variables-and-get-dummies" data-toc-modified-id="Encode-some-variables-and-get-dummies-7.1">Encode some variables and get dummies</a></span></li></ul></li></ul></div>

## Imports

In [193]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 

import matplotlib.cm as cm

from matplotlib.colors import Normalize

import statsmodels.formula.api as smf
import statsmodels.api as sm

from IPython.display import display_html,display, Markdown

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFECV
from sklearn.preprocessing import StandardScaler, LabelEncoder




np.set_printoptions(suppress=True, precision=7)
pd.set_option("display.max_columns",55)
print("Successfully imported all")

Successfully imported all

## Read data

In [194]:
dem = pd.read_csv("Demographics.csv",)
lab = pd.read_csv("Labour.csv")

df = pd.concat([dem,lab],axis=1)

## Model

**Looking at what factors determined a change in a persons salary**

In [195]:
dftemp = pd.concat([dem,lab],axis=1)

In [196]:
display(dftemp)
dftemp.shape

,age,gender,race,highest_grade,tertiary_edu,province_current,province_moved,province_before,province_during,labour_in_feb,work_days_feb,work_hours_feb,take_home_pay_feb,labour_in_apr,work_days_apr,work_hours_apr,take_home_pay_apr,lost_labour,kept_labour,return_to_work,usual_work
0,39.0,Man,White,Grade 9,No,Gauteng,No,NaN,NaN,1,NaN,NaN,180.0,0,0.0,0.0,0.0,1,0,0,Unknown
1,72.0,Woman,Asian/Indian,Grade 0,NaN,KwaZulu-Natal,No,NaN,NaN,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not Employed
2,30.0,Woman,African/Black,Grade 10,Yes,Gauteng,No,NaN,NaN,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not Employed
3,48.0,Woman,African/Black,Grade 10,No,Gauteng,No,NaN,NaN,1,3.0,5.0,900.0,0,0.0,0.0,0.0,1,0,1,Elementary occupations
4,49.0,Woman,African/Black,Grade 9,No,Gauteng,No,NaN,NaN,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not Employed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7068,22.0,Man,African/Black,Grade 11,No,Northern Cape,No,NaN,NaN,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not Employed
7069,24.0,Woman,Coloured,Grade 10,No,Western Cape,No,NaN,NaN,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not Employed
7070,36.0,Woman,African/Black,NTC 3,No,North West,No,NaN,NaN,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not Employed
7071,20.0,Man,African/Black,Grade 12,No,North West,Yes,Gauteng,Gauteng,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not Employed
7072,49.0,Man,Coloured,Grade 11,Yes,Western Cape,No,NaN,NaN,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not Employed

(7073, 21)

In [198]:
def fix_race(race):
    if race == "African/Black": return "Black"
    elif race == "Asian/Indian": return "AsInd"
    else: return race
    
    
def fix_province(provinceCurrent, provinceMoved, provinceBefore):
    if provinceMoved == "No":
        province = provinceCurrent
    else:
        province = provinceBefore
        
    return province

def fix_punc(province):
    prov = province.replace(" ", "_")
    prov = prov.replace("-", "_")

    return prov


    
def fix_work(work):
    new_work = work.replace(" ", "_")
    new_work = new_work.replace("-", "_")
    new_work = new_work.replace(",", "")
    return new_work



dftemp["race"] = np.vectorize(fix_race)(dftemp["race"])


#Fix province and puncuation
dftemp["province_before"] = np.vectorize(fix_province)(dftemp["province_current"],dftemp["province_moved"],dftemp["province_before"])

dftemp["province_during"] = np.vectorize(fix_province)(dftemp["province_current"],dftemp["province_moved"],dftemp["province_before"])

dftemp["province_before"] = np.vectorize(fix_punc)(dftemp["province_before"])

#Fix puncuation in usual work
dftemp["usual_work"] = np.vectorize(fix_work)(dftemp["usual_work"])


dftemp = dftemp[dftemp["province_moved"].notna() & (dftemp["province_moved"] != "nan") & (dftemp["province_before"] != "nan")]
display(dftemp)


# display(dftemp[dftemp["province_before"] == "nan"])

,age,gender,race,highest_grade,tertiary_edu,province_current,province_moved,province_before,province_during,labour_in_feb,work_days_feb,work_hours_feb,take_home_pay_feb,labour_in_apr,work_days_apr,work_hours_apr,take_home_pay_apr,lost_labour,kept_labour,return_to_work,usual_work
0,39.0,Man,White,Grade 9,No,Gauteng,No,Gauteng,Gauteng,1,NaN,NaN,180.0,0,0.0,0.0,0.0,1,0,0,Unknown
1,72.0,Woman,AsInd,Grade 0,NaN,KwaZulu-Natal,No,KwaZulu_Natal,KwaZulu-Natal,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not_Employed
2,30.0,Woman,Black,Grade 10,Yes,Gauteng,No,Gauteng,Gauteng,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not_Employed
3,48.0,Woman,Black,Grade 10,No,Gauteng,No,Gauteng,Gauteng,1,3.0,5.0,900.0,0,0.0,0.0,0.0,1,0,1,Elementary_occupations
4,49.0,Woman,Black,Grade 9,No,Gauteng,No,Gauteng,Gauteng,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not_Employed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7068,22.0,Man,Black,Grade 11,No,Northern Cape,No,Northern_Cape,Northern Cape,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not_Employed
7069,24.0,Woman,Coloured,Grade 10,No,Western Cape,No,Western_Cape,Western Cape,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not_Employed
7070,36.0,Woman,Black,NTC 3,No,North West,No,North_West,North West,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not_Employed
7071,20.0,Man,Black,Grade 12,No,North West,Yes,Gauteng,Gauteng,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not_Employed
7072,49.0,Man,Coloured,Grade 11,Yes,Western Cape,No,Western_Cape,Western Cape,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0,0,Not_Employed

In [199]:
# df_main = dftemp[["age","gender","race","highest_grade","province_current", "tertiary_edu","take_home_pay_feb", "take_home_pay_apr","kept_labour","usual_work"]]


df_main = dftemp[["age","gender","race","highest_grade", "tertiary_edu","province_current", "province_moved", "province_before","province_during","take_home_pay_feb", "take_home_pay_apr","kept_labour","usual_work"]]


df_main[df_main["province_moved"]=="Yes"]

,age,gender,race,highest_grade,tertiary_edu,province_current,province_moved,province_before,province_during,take_home_pay_feb,take_home_pay_apr,kept_labour,usual_work
49,41.0,Woman,Black,Grade 11,No,Gauteng,Yes,Gauteng,Gauteng,800.0,0.0,0,Unknown
53,32.0,Man,Black,Grade 10,Yes,Gauteng,Yes,Free_State,Free_State,6500.0,6500.0,1,Plant_and_machine_operators_and_assemblers
100,47.0,Woman,Black,Grade 12,Yes,Mpumalanga,Yes,Mpumalanga,Mpumalanga,0.0,0.0,0,Not_Employed
105,33.0,Man,Black,Grade 11,Yes,Mpumalanga,Yes,Mpumalanga,Mpumalanga,7000.0,NaN,1,Craft_and_related_trades_workers
143,47.0,Woman,Black,Grade 7,NaN,Gauteng,Yes,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6983,47.0,Woman,Black,Grade 12,No,Mpumalanga,Yes,Mpumalanga,Mpumalanga,11000.0,11000.0,1,Unknown
6988,58.0,Woman,Black,Grade 8,NaN,KwaZulu-Natal,Yes,KwaZulu_Natal,KwaZulu_Natal,0.0,0.0,0,Not_Employed
6992,23.0,Woman,Black,Grade 11,Yes,Gauteng,Yes,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
7052,31.0,Man,Black,Grade 12,Yes,Free State,Yes,Gauteng,Gauteng,NaN,0.0,0,Self_Employed
7071,20.0,Man,Black,Grade 12,No,North West,Yes,Gauteng,Gauteng,0.0,0.0,0,Not_Employed

### Drop all nans

In [174]:
display(df_main)
df_main_dropped_nans = df_main.dropna()
display(df_main_dropped_nans)

,age,gender,race,highest_grade,tertiary_edu,province_current,province_moved,province_before,province_during,take_home_pay_feb,take_home_pay_apr,kept_labour,usual_work
0,39.0,Man,White,Grade 9,No,Gauteng,No,Gauteng,Gauteng,180.0,0.0,0,Unknown
1,72.0,Woman,AsInd,Grade 0,NaN,KwaZulu-Natal,No,KwaZulu_Natal,KwaZulu-Natal,0.0,0.0,0,Not_Employed
2,30.0,Woman,Black,Grade 10,Yes,Gauteng,No,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
3,48.0,Woman,Black,Grade 10,No,Gauteng,No,Gauteng,Gauteng,900.0,0.0,0,Elementary_occupations
4,49.0,Woman,Black,Grade 9,No,Gauteng,No,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7068,22.0,Man,Black,Grade 11,No,Northern Cape,No,Northern_Cape,Northern Cape,0.0,0.0,0,Not_Employed
7069,24.0,Woman,Coloured,Grade 10,No,Western Cape,No,Western_Cape,Western Cape,0.0,0.0,0,Not_Employed
7070,36.0,Woman,Black,NTC 3,No,North West,No,North_West,North West,0.0,0.0,0,Not_Employed
7071,20.0,Man,Black,Grade 12,No,North West,Yes,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
7072,49.0,Man,Coloured,Grade 11,Yes,Western Cape,No,Western_Cape,Western Cape,0.0,0.0,0,Not_Employed

,age,gender,race,highest_grade,tertiary_edu,province_current,province_moved,province_before,province_during,take_home_pay_feb,take_home_pay_apr,kept_labour,usual_work
0,39.0,Man,White,Grade 9,No,Gauteng,No,Gauteng,Gauteng,180.0,0.0,0,Unknown
2,30.0,Woman,Black,Grade 10,Yes,Gauteng,No,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
3,48.0,Woman,Black,Grade 10,No,Gauteng,No,Gauteng,Gauteng,900.0,0.0,0,Elementary_occupations
4,49.0,Woman,Black,Grade 9,No,Gauteng,No,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
5,34.0,Man,Black,Grade 9,No,Gauteng,No,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7068,22.0,Man,Black,Grade 11,No,Northern Cape,No,Northern_Cape,Northern Cape,0.0,0.0,0,Not_Employed
7069,24.0,Woman,Coloured,Grade 10,No,Western Cape,No,Western_Cape,Western Cape,0.0,0.0,0,Not_Employed
7070,36.0,Woman,Black,NTC 3,No,North West,No,North_West,North West,0.0,0.0,0,Not_Employed
7071,20.0,Man,Black,Grade 12,No,North West,Yes,Gauteng,Gauteng,0.0,0.0,0,Not_Employed
7072,49.0,Man,Coloured,Grade 11,Yes,Western Cape,No,Western_Cape,Western Cape,0.0,0.0,0,Not_Employed

### Now this is the dataframe of all people who kept their jobs, and have usable data

In [171]:
# df_main_kept_labour = df_main_diff[(df_main_diff['kept_labour']==1) & (df_main_diff['salary_change']!="None")]


df_main_kept_labour = df_main_dropped_nans[(df_main_dropped_nans['kept_labour']==1)]

print(list(df_main_kept_labour))

display(df_main_kept_labour)

['age', 'gender', 'race', 'highest_grade', 'tertiary_edu', 'province_current', 'province_moved', 'province_before', 'province_during', 'take_home_pay_feb', 'take_home_pay_apr', 'kept_labour', 'usual_work']

,age,gender,race,highest_grade,tertiary_edu,province_current,province_moved,province_before,province_during,take_home_pay_feb,take_home_pay_apr,kept_labour,usual_work
15,52.0,Woman,Coloured,Grade 12,No,Gauteng,No,Gauteng,Gauteng,25000.0,25000.0,1,Technicians_and_associate_professionals
20,40.0,Woman,Black,Grade 11,No,Gauteng,No,Gauteng,Gauteng,3500.0,3500.0,1,Technicians_and_associate_professionals
41,37.0,Woman,Black,Grade 12,Yes,Gauteng,No,Gauteng,Gauteng,4600.0,4600.0,1,Professionals
44,45.0,Woman,Black,Grade 12,Yes,Gauteng,No,Gauteng,Gauteng,4000.0,4200.0,1,Service_and_sales_workers
45,39.0,Woman,Black,Grade 11,Yes,Gauteng,No,Gauteng,Gauteng,3500.0,7200.0,1,Professionals
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7001,43.0,Woman,Black,Grade 9,No,Eastern Cape,No,Eastern_Cape,Eastern Cape,3200.0,3200.0,1,Elementary_occupations
7016,29.0,Man,Black,Grade 10,No,North West,No,North_West,North West,4400.0,4500.0,1,Service_and_sales_workers
7018,30.0,Woman,Black,Grade 12,Yes,Free State,No,Free_State,Free State,24000.0,12000.0,1,Professionals
7021,27.0,Woman,Black,Grade 9,No,Limpopo,No,Limpopo,Limpopo,1500.0,2800.0,1,Unknown
7038,25.0,Woman,Black,Grade 12,Yes,Gauteng,No,Gauteng,Gauteng,5430.0,5430.0,1,Clerical_support_workers

### Calculate and store salary difference

In [9]:

diff = df_main_kept_labour['take_home_pay_apr'] - df_main_kept_labour['take_home_pay_feb']

display(diff)

perc = (diff/df_main_kept_labour['take_home_pay_feb'])* 100

perc = np.nan_to_num(perc)
# display(perc)

df_main_diff = df_main_kept_labour.copy()

df_main_diff['take_home_pay_difference'] = perc

15          0.0
20          0.0
41          0.0
44        200.0
45       3700.0
         ...
7001        0.0
7016      100.0
7018   -12000.0
7021     1300.0
7038        0.0
Length: 706, dtype: float64

### Remove outliers

In [10]:
print("Min percentage change before: ",min(df_main_diff['take_home_pay_difference']))
print("Max percentage change before: ", max(df_main_diff['take_home_pay_difference']))

# Removing Income outliers
df_no_outliers = df_main_diff[df_main_diff["take_home_pay_difference"]<np.percentile(a = df_main_diff["take_home_pay_difference"], q =98)]


print("\n\n\nMin percentage change after: ",min(df_no_outliers['take_home_pay_difference']))
print("Max percentage change after: ",max(df_no_outliers['take_home_pay_difference']))
display(df_no_outliers)

Min percentage change before:  -100.0
Max percentage change before:  1.7976931348623157e+308



Min percentage change after:  -100.0
Max percentage change after:  135.29411764705884

,age,gender,race,highest_grade,tertiary_edu,province_before,take_home_pay_feb,take_home_pay_apr,kept_labour,usual_work,take_home_pay_difference
15,52.0,Woman,Coloured,Grade 12,No,Gauteng,25000.0,25000.0,1,Technicians_and_associate_professionals,0.000000
20,40.0,Woman,Black,Grade 11,No,Gauteng,3500.0,3500.0,1,Technicians_and_associate_professionals,0.000000
41,37.0,Woman,Black,Grade 12,Yes,Gauteng,4600.0,4600.0,1,Professionals,0.000000
44,45.0,Woman,Black,Grade 12,Yes,Gauteng,4000.0,4200.0,1,Service_and_sales_workers,5.000000
45,39.0,Woman,Black,Grade 11,Yes,Gauteng,3500.0,7200.0,1,Professionals,105.714286
...,...,...,...,...,...,...,...,...,...,...,...
7001,43.0,Woman,Black,Grade 9,No,Eastern_Cape,3200.0,3200.0,1,Elementary_occupations,0.000000
7016,29.0,Man,Black,Grade 10,No,North_West,4400.0,4500.0,1,Service_and_sales_workers,2.272727
7018,30.0,Woman,Black,Grade 12,Yes,Free_State,24000.0,12000.0,1,Professionals,-50.000000
7021,27.0,Woman,Black,Grade 9,No,Limpopo,1500.0,2800.0,1,Unknown,86.666667
7038,25.0,Woman,Black,Grade 12,Yes,Gauteng,5430.0,5430.0,1,Clerical_support_workers,0.000000

In [30]:
df_newvars = df_no_outliers.copy()

def check_youth(age):
    if age<25: return 1
    else: return 0 

def check_male(gender): 
    if gender == "Man": return 1
    else: return 0
    
def check_female(gender): 
    if gender == "Woman": return 1
    else: return 0
    

def check_matric(highest_grade):
    if highest_grade == "Grade 12": return 1
    else: return 0

def check_tertedu(tertiary_edu):
    if tertiary_edu == "Yes" : return 1 
    else: return 0 
    
def check_work(work):
    new_work = work.replace(" ", "_")
    new_work = new_work.replace("-", "_")
    new_work = new_work.replace(",", "")
    return new_work


def check_white(race):
    if race == "White": return 1
    else: return 0
    
def check_black(race):
    if race == "Black": return 1
    else: return 0

    
XYZ = pd.DataFrame()
XYZ["Age"] = df_newvars["age"]
XYZ["Youth"] = np.vectorize(check_youth)(df_newvars["age"])

# XYZ["Race"] = np.vectorize(check_race)(df_newvars["race"])



XYZ["Black"] = np.vectorize(check_black)(df_newvars["race"])
XYZ["White"] = np.vectorize(check_white)(df_newvars["race"])


XYZ["Race"] = df_newvars["race"]


XYZ["Male"] = np.vectorize(check_male)(df_newvars["gender"])

XYZ["Female"] = np.vectorize(check_female)(df_newvars["gender"])


XYZ["Matric"] = np.vectorize(check_matric)(df_newvars["highest_grade"])
XYZ["Tertiary"] = np.vectorize(check_tertedu)(df_newvars["tertiary_edu"])


XYZ["Province"] = df_newvars["province_before"]


XYZ["Usual_Work"] = np.vectorize(check_work)(df_newvars['usual_work']) 

display(XYZ)

,Age,Youth,Black,White,Race,Male,Female,Matric,Tertiary,Province,Usual_Work
15,52.0,0,0,0,Coloured,0,1,1,0,Gauteng,Technicians_and_associate_professionals
20,40.0,0,1,0,Black,0,1,0,0,Gauteng,Technicians_and_associate_professionals
41,37.0,0,1,0,Black,0,1,1,1,Gauteng,Professionals
44,45.0,0,1,0,Black,0,1,1,1,Gauteng,Service_and_sales_workers
45,39.0,0,1,0,Black,0,1,0,1,Gauteng,Professionals
...,...,...,...,...,...,...,...,...,...,...,...
7001,43.0,0,1,0,Black,0,1,0,0,Eastern_Cape,Elementary_occupations
7016,29.0,0,1,0,Black,1,0,0,0,North_West,Service_and_sales_workers
7018,30.0,0,1,0,Black,0,1,1,1,Free_State,Professionals
7021,27.0,0,1,0,Black,0,1,0,0,Limpopo,Unknown
7038,25.0,0,1,0,Black,0,1,1,1,Gauteng,Clerical_support_workers

### Determine if salary changed and create new variable for this

In [31]:
def salary_change(diff):
    if diff==0:
        return "unchanged"
    else:
        return "changed"
    

def salary_diff(diff):
    if diff==0:
        return "unchanged"
    elif diff>0:
        return "increased"
    elif diff<0:
        return "decreased"
    
    
def salary_decreased(diff):
    if diff<0:
        return "decreased"
    else:
        return "did_not_decrease"
    
def salary_increased(diff):
    if diff>0:
        return "increased"
    else:
        return "did_not_increased"
    
    
def salary_inc_dec(diff):
    if diff<0:
        return "decreased"
    elif diff>0:
        return "increased"
    else:
        return "none"


XYZ["Pay_Feb"] = df_newvars["take_home_pay_feb"]
XYZ["Pay_Apr"] = df_newvars["take_home_pay_apr"]

XYZ["Pay_Diff"] = df_newvars['take_home_pay_difference']
XYZ["Salary_Change"] = np.vectorize(salary_change)(df_newvars['take_home_pay_difference']) 
XYZ["Salary_Diff"] = np.vectorize(salary_diff)(df_newvars['take_home_pay_difference']) 
XYZ["Salary_Decreased"] = np.vectorize(salary_decreased)(df_newvars['take_home_pay_difference']) 
XYZ["Salary_Increased"] = np.vectorize(salary_increased)(df_newvars['take_home_pay_difference']) 

XYZ["Salary_IncDec"] = np.vectorize(salary_inc_dec)(df_newvars['take_home_pay_difference']) 

#Normalize salaries
# XYZ["Pay_Feb"] = XYZ["Pay_Feb"] = (XYZ["Pay_Feb"]-XYZ["Pay_Feb"].min())/ (XYZ["Pay_Feb"].max()-XYZ["Pay_Feb"].min())

# XYZ["Pay_Apr"] = XYZ["Pay_Apr"] = (XYZ["Pay_Apr"]-XYZ["Pay_Apr"].min())/ (XYZ["Pay_Apr"].max()-XYZ["Pay_Apr"].min())

# XYZ["Pay_Diff"] = XYZ["Pay_Diff"] = (XYZ["Pay_Diff"]-XYZ["Pay_Diff"].min())/ (XYZ["Pay_Diff"].max()-XYZ["Pay_Diff"].min())

display(XYZ)

,Age,Youth,Black,White,Race,Male,Female,Matric,Tertiary,Province,Usual_Work,Pay_Feb,Pay_Apr,Pay_Diff,Salary_Change,Salary_Diff,Salary_Decreased,Salary_Increased,Salary_IncDec
15,52.0,0,0,0,Coloured,0,1,1,0,Gauteng,Technicians_and_associate_professionals,25000.0,25000.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none
20,40.0,0,1,0,Black,0,1,0,0,Gauteng,Technicians_and_associate_professionals,3500.0,3500.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none
41,37.0,0,1,0,Black,0,1,1,1,Gauteng,Professionals,4600.0,4600.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none
44,45.0,0,1,0,Black,0,1,1,1,Gauteng,Service_and_sales_workers,4000.0,4200.0,5.000000,changed,increased,did_not_decrease,increased,increased
45,39.0,0,1,0,Black,0,1,0,1,Gauteng,Professionals,3500.0,7200.0,105.714286,changed,increased,did_not_decrease,increased,increased
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7001,43.0,0,1,0,Black,0,1,0,0,Eastern_Cape,Elementary_occupations,3200.0,3200.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none
7016,29.0,0,1,0,Black,1,0,0,0,North_West,Service_and_sales_workers,4400.0,4500.0,2.272727,changed,increased,did_not_decrease,increased,increased
7018,30.0,0,1,0,Black,0,1,1,1,Free_State,Professionals,24000.0,12000.0,-50.000000,changed,decreased,decreased,did_not_increased,decreased
7021,27.0,0,1,0,Black,0,1,0,0,Limpopo,Unknown,1500.0,2800.0,86.666667,changed,increased,did_not_decrease,increased,increased
7038,25.0,0,1,0,Black,0,1,1,1,Gauteng,Clerical_support_workers,5430.0,5430.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none

## Check value counts of salary change

In [32]:
display(Markdown("## Salary Change Value Counts"))
print(XYZ["Salary_Change"].value_counts())

## Salary Change Value Counts

unchanged    423
changed      268
Name: Salary_Change, dtype: int64

## Check details of work type

In [33]:
display(Markdown("## Work type with Salary_Change == \"decreased\""))
print(XYZ[XYZ["Salary_Change"]=="decreased"]["Usual_Work"].value_counts())

display(Markdown("## Work type with Salary_Change == \"increased\""))
print(XYZ[XYZ["Salary_Change"]=="increased"]["Usual_Work"].value_counts())

display(Markdown("## Work type with Salary_Change == \"unchanged\""))
print(XYZ[XYZ["Salary_Change"]=="unchanged"]["Usual_Work"].value_counts())

display(Markdown("## Work type with Salary_Change == \"changed\""))
print(XYZ[XYZ["Salary_Change"]=="changed"]["Usual_Work"].value_counts())

display(Markdown("## Work type with Salary_Change == \"did_not_decrease\""))
print(XYZ[XYZ["Salary_Change"]=="did_not_decrease"]["Usual_Work"].value_counts())

display(Markdown("## Work Type Value Counts"))
print(XYZ["Usual_Work"].value_counts())

## Work type with Salary_Change == "decreased"

Series([], Name: Usual_Work, dtype: int64)

## Work type with Salary_Change == "increased"

Series([], Name: Usual_Work, dtype: int64)

## Work type with Salary_Change == "unchanged"

Professionals                                        93
Elementary_occupations                               72
Service_and_sales_workers                            68
Technicians_and_associate_professionals              54
Clerical_support_workers                             52
Managers                                             34
Plant_and_machine_operators_and_assemblers           25
Craft_and_related_trades_workers                     15
Unknown                                               8
Self_Employed                                         1
Skilled_agricultural_forestry_and_fishery_workers     1
Name: Usual_Work, dtype: int64

## Work type with Salary_Change == "changed"

Service_and_sales_workers                            78
Professionals                                        40
Elementary_occupations                               40
Clerical_support_workers                             31
Plant_and_machine_operators_and_assemblers           20
Technicians_and_associate_professionals              18
Craft_and_related_trades_workers                     15
Managers                                             15
Unknown                                               5
Skilled_agricultural_forestry_and_fishery_workers     2
Self_Employed                                         1
Armed_forces_occupations                              1
Not_applicable                                        1
Not_Employed                                          1
Name: Usual_Work, dtype: int64

## Work type with Salary_Change == "did_not_decrease"

Series([], Name: Usual_Work, dtype: int64)

## Work Type Value Counts

Service_and_sales_workers                            146
Professionals                                        133
Elementary_occupations                               112
Clerical_support_workers                              83
Technicians_and_associate_professionals               72
Managers                                              49
Plant_and_machine_operators_and_assemblers            45
Craft_and_related_trades_workers                      30
Unknown                                               13
Skilled_agricultural_forestry_and_fishery_workers      3
Self_Employed                                          2
Not_Employed                                           1
Armed_forces_occupations                               1
Not_applicable                                         1
Name: Usual_Work, dtype: int64

### Remove all nonsensical dara (not applicable and unknown) and jobs with too few occurences

In [34]:
XYZ = XYZ[XYZ.groupby("Usual_Work")["Usual_Work"].transform(len) > 15]
XYZ["Usual_Work"].value_counts()

Service_and_sales_workers                     146
Professionals                                 133
Elementary_occupations                        112
Clerical_support_workers                       83
Technicians_and_associate_professionals        72
Managers                                       49
Plant_and_machine_operators_and_assemblers     45
Craft_and_related_trades_workers               30
Name: Usual_Work, dtype: int64

## Check details of province

In [35]:
display(Markdown("## Province with Salary_Change == \"decreased\""))
print(XYZ[XYZ["Salary_Change"]=="decreased"]["Province"].value_counts())

display(Markdown("## Province with Salary_Change == \"increased\""))
print(XYZ[XYZ["Salary_Change"]=="increased"]["Province"].value_counts())

display(Markdown("## Province with Salary_Change == \"unchanged\""))
print(XYZ[XYZ["Salary_Change"]=="unchanged"]["Province"].value_counts())

display(Markdown("## Province with Salary_Change == \"changed\""))
print(XYZ[XYZ["Salary_Change"]=="changed"]["Province"].value_counts())

display(Markdown("## Province with Salary_Change == \"did_not_decrease\""))
print(XYZ[XYZ["Salary_Change"]=="did_not_decrease"]["Province"].value_counts())

display(Markdown("## Province Value Counts"))
print(XYZ["Province"].value_counts())

## Province with Salary_Change == "decreased"

Series([], Name: Province, dtype: int64)

## Province with Salary_Change == "increased"

Series([], Name: Province, dtype: int64)

## Province with Salary_Change == "unchanged"

Gauteng          87
KwaZulu_Natal    77
Western_Cape     54
Eastern_Cape     44
Mpumalanga       42
Northern_Cape    38
Limpopo          26
Free_State       24
North_West       20
nan               1
Name: Province, dtype: int64

## Province with Salary_Change == "changed"

Gauteng          69
KwaZulu_Natal    47
Mpumalanga       36
Free_State       25
Eastern_Cape     20
Northern_Cape    17
Limpopo          16
Western_Cape     16
North_West       11
Name: Province, dtype: int64

## Province with Salary_Change == "did_not_decrease"

Series([], Name: Province, dtype: int64)

## Province Value Counts

Gauteng          156
KwaZulu_Natal    124
Mpumalanga        78
Western_Cape      70
Eastern_Cape      64
Northern_Cape     55
Free_State        49
Limpopo           42
North_West        31
nan                1
Name: Province, dtype: int64

In [36]:
XYZ = XYZ[XYZ.groupby("Province")["Province"].transform(len) > 1]
XYZ["Province"].value_counts()

Gauteng          156
KwaZulu_Natal    124
Mpumalanga        78
Western_Cape      70
Eastern_Cape      64
Northern_Cape     55
Free_State        49
Limpopo           42
North_West        31
Name: Province, dtype: int64

In [37]:
XYZ["Race"].value_counts()
XYZ = XYZ[XYZ["Race"] != "nan"]

XYZ

,Age,Youth,Black,White,Race,Male,Female,Matric,Tertiary,Province,Usual_Work,Pay_Feb,Pay_Apr,Pay_Diff,Salary_Change,Salary_Diff,Salary_Decreased,Salary_Increased,Salary_IncDec
15,52.0,0,0,0,Coloured,0,1,1,0,Gauteng,Technicians_and_associate_professionals,25000.0,25000.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none
20,40.0,0,1,0,Black,0,1,0,0,Gauteng,Technicians_and_associate_professionals,3500.0,3500.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none
41,37.0,0,1,0,Black,0,1,1,1,Gauteng,Professionals,4600.0,4600.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none
44,45.0,0,1,0,Black,0,1,1,1,Gauteng,Service_and_sales_workers,4000.0,4200.0,5.000000,changed,increased,did_not_decrease,increased,increased
45,39.0,0,1,0,Black,0,1,0,1,Gauteng,Professionals,3500.0,7200.0,105.714286,changed,increased,did_not_decrease,increased,increased
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6982,35.0,0,1,0,Black,0,1,1,1,Mpumalanga,Service_and_sales_workers,5200.0,5300.0,1.923077,changed,increased,did_not_decrease,increased,increased
7001,43.0,0,1,0,Black,0,1,0,0,Eastern_Cape,Elementary_occupations,3200.0,3200.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none
7016,29.0,0,1,0,Black,1,0,0,0,North_West,Service_and_sales_workers,4400.0,4500.0,2.272727,changed,increased,did_not_decrease,increased,increased
7018,30.0,0,1,0,Black,0,1,1,1,Free_State,Professionals,24000.0,12000.0,-50.000000,changed,decreased,decreased,did_not_increased,decreased
7038,25.0,0,1,0,Black,0,1,1,1,Gauteng,Clerical_support_workers,5430.0,5430.0,0.000000,unchanged,unchanged,did_not_decrease,did_not_increased,none

### Encode some variables and get dummies

In [38]:
# df_dummies = pd.get_dummies(df_encoded, columns=["race","highest_grade","province_current", "usual_work"], drop_first=True)

LE = LabelEncoder()

# df_dummies = XYZ.copy()

df_dummies = pd.get_dummies(XYZ, columns=["Race","Usual_Work", "Province"])

# df_dummies = pd.get_dummies(XYZ, columns=["Race","Province","Usual_Work"], drop_first=True)

# df_dummies["Race"] = LE.fit_transform(df_dummies["Race"])
# df_dummies["Usual_Work"] = LE.fit_transform(df_dummies["Usual_Work"])
df_dummies["Salary_Change"] = 1 - LE.fit_transform(df_dummies["Salary_Change"])
df_dummies["Salary_Decreased"] = 1 - LE.fit_transform(df_dummies["Salary_Decreased"])
df_dummies["Salary_Increased"] = LE.fit_transform(df_dummies["Salary_Increased"])

df_dummies["Salary_Diff"] = 1 - LE.fit_transform(df_dummies["Salary_Diff"])
df_dummies["Salary_IncDec"] = 1 - LE.fit_transform(df_dummies["Salary_IncDec"])


display(df_dummies)
print(df_dummies.columns)

,Age,Youth,Black,White,Male,Female,Matric,Tertiary,Pay_Feb,Pay_Apr,Pay_Diff,Salary_Change,Salary_Diff,Salary_Decreased,Salary_Increased,Salary_IncDec,Race_AsInd,Race_Black,Race_Coloured,Race_White,Usual_Work_Clerical_support_workers,Usual_Work_Craft_and_related_trades_workers,Usual_Work_Elementary_occupations,Usual_Work_Managers,Usual_Work_Plant_and_machine_operators_and_assemblers,Usual_Work_Professionals,Usual_Work_Service_and_sales_workers,Usual_Work_Technicians_and_associate_professionals,Province_Eastern_Cape,Province_Free_State,Province_Gauteng,Province_KwaZulu_Natal,Province_Limpopo,Province_Mpumalanga,Province_North_West,Province_Northern_Cape,Province_Western_Cape
15,52.0,0,0,0,0,1,1,0,25000.0,25000.0,0.000000,0,-1,0,0,-1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
20,40.0,0,1,0,0,1,0,0,3500.0,3500.0,0.000000,0,-1,0,0,-1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
41,37.0,0,1,0,0,1,1,1,4600.0,4600.0,0.000000,0,-1,0,0,-1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
44,45.0,0,1,0,0,1,1,1,4000.0,4200.0,5.000000,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0
45,39.0,0,1,0,0,1,0,1,3500.0,7200.0,105.714286,1,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6982,35.0,0,1,0,0,1,1,1,5200.0,5300.0,1.923077,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
7001,43.0,0,1,0,0,1,0,0,3200.0,3200.0,0.000000,0,-1,0,0,-1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
7016,29.0,0,1,0,1,0,0,0,4400.0,4500.0,2.272727,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
7018,30.0,0,1,0,0,1,1,1,24000.0,12000.0,-50.000000,1,1,1,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
7038,25.0,0,1,0,0,1,1,1,5430.0,5430.0,0.000000,0,-1,0,0,-1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

Index(['Age', 'Youth', 'Black', 'White', 'Male', 'Female', 'Matric',
       'Tertiary', 'Pay_Feb', 'Pay_Apr', 'Pay_Diff', 'Salary_Change',
       'Salary_Diff', 'Salary_Decreased', 'Salary_Increased', 'Salary_IncDec',
       'Race_AsInd', 'Race_Black', 'Race_Coloured', 'Race_White',
       'Usual_Work_Clerical_support_workers',
       'Usual_Work_Craft_and_related_trades_workers',
       'Usual_Work_Elementary_occupations', 'Usual_Work_Managers',
       'Usual_Work_Plant_and_machine_operators_and_assemblers',
       'Usual_Work_Professionals', 'Usual_Work_Service_and_sales_workers',
       'Usual_Work_Technicians_and_associate_professionals',
       'Province_Eastern_Cape', 'Province_Free_State', 'Province_Gauteng',
       'Province_KwaZulu_Natal', 'Province_Limpopo', 'Province_Mpumalanga',
       'Province_North_West', 'Province_Northern_Cape',
       'Province_Western_Cape'],
      dtype='object')

# Train Test SPlit

In [94]:
train, test = train_test_split(df_dummies,test_size=0.2, random_state=100)

In [50]:
cols = df_dummies.columns.values
cols =  " + ".join(cols)
cols

'Age + Youth + Black + White + Male + Female + Matric + Tertiary + Pay_Feb + Pay_Apr + Pay_Diff + Salary_Change + Salary_Diff + Salary_Decreased + Salary_Increased + Salary_IncDec + Race_AsInd + Race_Black + Race_Coloured + Race_White + Usual_Work_Clerical_support_workers + Usual_Work_Craft_and_related_trades_workers + Usual_Work_Elementary_occupations + Usual_Work_Managers + Usual_Work_Plant_and_machine_operators_and_assemblers + Usual_Work_Professionals + Usual_Work_Service_and_sales_workers + Usual_Work_Technicians_and_associate_professionals + Province_Eastern_Cape + Province_Free_State + Province_Gauteng + Province_KwaZulu_Natal + Province_Limpopo + Province_Mpumalanga + Province_North_West + Province_Northern_Cape + Province_Western_Cape'

# LOGISTIC

In [53]:
fuk = smf.logit(formula = "Salary_Change ~ Age + Youth + Black + White + Male + Female + Matric + Tertiary + Pay_Feb + Pay_Apr + Pay_Diff + Race_AsInd + Race_Black + Race_Coloured + Race_White + Usual_Work_Clerical_support_workers + Usual_Work_Craft_and_related_trades_workers + Usual_Work_Elementary_occupations + Usual_Work_Managers + Usual_Work_Plant_and_machine_operators_and_assemblers + Usual_Work_Professionals + Usual_Work_Service_and_sales_workers + Usual_Work_Technicians_and_associate_professionals + Province_Eastern_Cape + Province_Free_State + Province_Gauteng + Province_KwaZulu_Natal + Province_Limpopo + Province_Mpumalanga + Province_North_West + Province_Northern_Cape + Province_Western_Cape", data=df_dummies).fit()
fuk.summary()

Optimization terminated successfully.
         Current function value: 0.585536
         Iterations 11

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:          Salary_Change   No. Observations:                  668
Model:                          Logit   Df Residuals:                      641
Method:                           MLE   Df Model:                           26
Date:                Sun, 20 Jun 2021   Pseudo R-squ.:                  0.1213
Time:                        18:44:49   Log-Likelihood:                -391.14
converged:                       True   LL-Null:                       -445.11
Covariance Type:            nonrobust   LLR p-value:                 5.921e-12
=========================================================================================================================
                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------
Intercept                                                -4.6310   6.45e+06  -7.17e-07      1.000   -1.27e+07    1.27e+07
Age                                                      -0.0133      0.011     -1.221      0.222      -0.035       0.008
Youth                                                    -0.0908      0.447     -0.203      0.839      -0.967       0.786
Black                                                     0.0588   8.12e+06   7.24e-09      1.000   -1.59e+07    1.59e+07
White                                                     0.0136   2.18e+07   6.21e-10      1.000   -4.28e+07    4.28e+07
Male                                                      4.7539   5.15e+06   9.23e-07      1.000   -1.01e+07    1.01e+07
Female                                                    4.7810   5.41e+06   8.84e-07      1.000   -1.06e+07    1.06e+07
Matric                                                   -0.1723      0.205     -0.839      0.401      -0.575       0.230
Tertiary                                                 -0.2853      0.205     -1.390      0.165      -0.688       0.117
Pay_Feb                                                   0.0001   4.97e-05      2.125      0.034    8.19e-06       0.000
Pay_Apr                                                  -0.0001   5.26e-05     -2.483      0.013      -0.000   -2.75e-05
Pay_Diff                                                 -0.0121      0.004     -2.747      0.006      -0.021      -0.003
Race_AsInd                                               -0.3600   2.14e+06  -1.69e-07      1.000   -4.18e+06    4.18e+06
Race_Black                                                0.0588   4.45e+06   1.32e-08      1.000   -8.73e+06    8.73e+06
Race_Coloured                                             0.3787   3.17e+06   1.19e-07      1.000   -6.22e+06    6.22e+06
Race_White                                                0.0136   2.29e+07   5.93e-10      1.000   -4.48e+07    4.48e+07
Usual_Work_Clerical_support_workers                      -0.0661        nan        nan        nan         nan         nan
Usual_Work_Craft_and_related_trades_workers               0.4159        nan        nan        nan         nan         nan
Usual_Work_Elementary_occupations                        -0.3301        nan        nan        nan         nan         nan
Usual_Work_Managers                                      -0.0317        nan        nan        nan         nan         nan
Usual_Work_Plant_and_machine_operators_and_assemblers     0.2856        nan        nan        nan         nan         nan
Usual_Work_Professionals                                 -0.0242        nan        nan        nan         nan         nan
Usual_Work_Service_and_sales_workers                      0.6349        nan        nan        nan         nan         nan
Usual_Work_Technicians_and_associate_professionals       -0.7932        nan        nan        nan         nan         nan
Province_Eastern_Cape                                    -0.2243   9.29e+06  -2.41e-08      1.000   -1.82e+07    1.82e+07
Province_Free_State                                       0.5086   9.29e+06   5.47e-08      1.000   -1.82e+07    1.82e+07
Province_Gauteng                                          0.3794   9.29e+06   4.08e-08      1.000   -1.82e+07    1.82e+07
Province_KwaZulu_Natal                                    0.0873   9.29e+06   9.39e-09      1.000   -1.82e+07    1.82e+07
Province_Limpopo                                          0.0561   9.29e+06   6.04e-09      1.000   -1.82e+07    1.82e+07
Province_Mpumalanga                                       0.3722   9.29e+06   4.01e-08      1.000   -1.82e+07    1.82e+07
Province_North_West                                      -0.0372   9.29e+06     -4e-09      1.000   -1.82e+07    1.82e+07
Province_Northern_Cape                                   -0.3875   9.29e+06  -4.17e-08      1.000   -1.82e+07    1.82e+07
Province_Western_Cape                                    -0.6637   9.29e+06  -7.14e-08      1.000   -1.82e+07    1.82e+07
=========================================================================================================================
"""

In [88]:
fuk = smf.logit(formula = "Salary_Change ~ Age + Black + Male + Matric + Tertiary + Pay_Feb", data=df_dummies).fit()
fuk.summary()

Optimization terminated successfully.
         Current function value: 0.652985
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:          Salary_Change   No. Observations:                  668
Model:                          Logit   Df Residuals:                      661
Method:                           MLE   Df Model:                            6
Date:                Sun, 20 Jun 2021   Pseudo R-squ.:                 0.02003
Time:                        18:56:32   Log-Likelihood:                -436.19
converged:                       True   LL-Null:                       -445.11
Covariance Type:            nonrobust   LLR p-value:                  0.006664
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0219      0.437      0.050      0.960      -0.835       0.879
Age           -0.0142      0.009     -1.553      0.120      -0.032       0.004
Black          0.4288      0.203      2.111      0.035       0.031       0.827
Male          -0.0029      0.166     -0.017      0.986      -0.329       0.323
Matric        -0.1112      0.189     -0.588      0.557      -0.482       0.260
Tertiary      -0.3153      0.185     -1.700      0.089      -0.679       0.048
Pay_Feb    -4.083e-06   9.39e-06     -0.435      0.664   -2.25e-05    1.43e-05
==============================================================================
"""

In [121]:
fuk = sm.OLS(train["Salary_Increased"], train[["Age","Tertiary","Usual_Work_Service_and_sales_workers"]]).fit(disp=0)
fuk.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:       Salary_Increased   R-squared (uncentered):                   0.163
Model:                            OLS   Adj. R-squared (uncentered):              0.158
Method:                 Least Squares   F-statistic:                              34.44
Date:                Sun, 20 Jun 2021   Prob (F-statistic):                    2.38e-20
Time:                        19:38:01   Log-Likelihood:                         -234.83
No. Observations:                 534   AIC:                                      475.7
Df Residuals:                     531   BIC:                                      488.5
Df Model:                           3
Covariance Type:            nonrobust
========================================================================================================
                                           coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Age                                      0.0035      0.001      5.899      0.000       0.002       0.005
Tertiary                                -0.0223      0.032     -0.706      0.480      -0.084       0.040
Usual_Work_Service_and_sales_workers     0.1201      0.038      3.129      0.002       0.045       0.195
==============================================================================
Omnibus:                      149.486   Durbin-Watson:                   2.004
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              284.735
Skew:                           1.703   Prob(JB):                     1.48e-62
Kurtosis:                       4.096   Cond. No.                         94.5
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [117]:
fuk = smf.logit(formula = "Salary_Increased ~ Age + Tertiary + Usual_Work_Service_and_sales_workers -1", data=train).fit()
fuk.summary()

Optimization terminated successfully.
         Current function value: 0.443321
         Iterations 6

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:       Salary_Increased   No. Observations:                  534
Model:                          Logit   Df Residuals:                      531
Method:                           MLE   Df Model:                            2
Date:                Sun, 20 Jun 2021   Pseudo R-squ.:                 0.02258
Time:                        19:07:21   Log-Likelihood:                -236.73
converged:                       True   LL-Null:                       -242.20
Covariance Type:            nonrobust   LLR p-value:                  0.004215
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Age                                     -0.0388      0.004     -8.774      0.000      -0.047      -0.030
Tertiary                                -0.5311      0.231     -2.302      0.021      -0.983      -0.079
Usual_Work_Service_and_sales_workers     0.5040      0.252      1.998      0.046       0.010       0.998
========================================================================================================
"""

In [112]:
a = smf.logit(formula = "Salary_Increased ~ Race_White + Race_Black", data=df_dummies).fit()
a.summary()

Optimization terminated successfully.
         Current function value: 0.431711
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:       Salary_Increased   No. Observations:                  668
Model:                          Logit   Df Residuals:                      665
Method:                           MLE   Df Model:                            2
Date:                Sun, 20 Jun 2021   Pseudo R-squ.:                 0.01877
Time:                        19:05:56   Log-Likelihood:                -288.38
converged:                       True   LL-Null:                       -293.90
Covariance Type:            nonrobust   LLR p-value:                  0.004023
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -2.1861      0.334     -6.554      0.000      -2.840      -1.532
Race_White    -0.4386      0.571     -0.769      0.442      -1.557       0.680
Race_Black     0.7089      0.353      2.008      0.045       0.017       1.401
==============================================================================
"""

In [63]:
a = smf.logit(formula = "Salary_Change ~ Black", data=df_dummies).fit()
a.summary()

Optimization terminated successfully.
         Current function value: 0.659387
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:          Salary_Change   No. Observations:                  668
Model:                          Logit   Df Residuals:                      666
Method:                           MLE   Df Model:                            1
Date:                Sun, 20 Jun 2021   Pseudo R-squ.:                 0.01042
Time:                        18:46:41   Log-Likelihood:                -440.47
converged:                       True   LL-Null:                       -445.11
Covariance Type:            nonrobust   LLR p-value:                  0.002317
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.9002      0.168     -5.367      0.000      -1.229      -0.571
Black          0.5699      0.191      2.986      0.003       0.196       0.944
==============================================================================
"""

In [533]:
argh = smf.logit(formula = "Salary_Increased ~  Usual_Work_Craft_and_related_trades_workers + Usual_Work_Clerical_support_workers + Usual_Work_Plant_and_machine_operators_and_assemblers + Usual_Work_Professionals + Usual_Work_Service_and_sales_workers + Usual_Work_Technicians_and_associate_professionals", data=df_dummies).fit()
argh.summary()

Optimization terminated successfully.
         Current function value: 0.421480
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:       Salary_Increased   No. Observations:                  668
Model:                          Logit   Df Residuals:                      661
Method:                           MLE   Df Model:                            6
Date:                Sat, 19 Jun 2021   Pseudo R-squ.:                 0.04202
Time:                        19:08:38   Log-Likelihood:                -281.55
converged:                       True   LL-Null:                       -293.90
Covariance Type:            nonrobust   LLR p-value:                 0.0003882
=========================================================================================================================
                                                            coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------
Intercept                                                -1.8827      0.234     -8.038      0.000      -2.342      -1.424
Usual_Work_Craft_and_related_trades_workers               0.6931      0.491      1.411      0.158      -0.269       1.656
Usual_Work_Clerical_support_workers                       0.1050      0.390      0.269      0.788      -0.660       0.870
Usual_Work_Plant_and_machine_operators_and_assemblers     0.6300      0.428      1.471      0.141      -0.209       1.469
Usual_Work_Professionals                                 -0.1069      0.355     -0.301      0.763      -0.802       0.589
Usual_Work_Service_and_sales_workers                      0.8382      0.301      2.787      0.005       0.249       1.428
Usual_Work_Technicians_and_associate_professionals       -1.2528      0.635     -1.974      0.048      -2.497      -0.009
=========================================================================================================================
"""

In [85]:
argh = smf.logit(formula = "Salary_Decreased ~ Male + Black + Tertiary", data=df_dummies).fit()
argh.summary()

Optimization terminated successfully.
         Current function value: 0.529866
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:       Salary_Decreased   No. Observations:                  668
Model:                          Logit   Df Residuals:                      664
Method:                           MLE   Df Model:                            3
Date:                Sun, 20 Jun 2021   Pseudo R-squ.:                0.005147
Time:                        18:53:46   Log-Likelihood:                -353.95
converged:                       True   LL-Null:                       -355.78
Covariance Type:            nonrobust   LLR p-value:                    0.3003
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.1083      0.243     -4.567      0.000      -1.584      -0.633
Male          -0.2499      0.187     -1.334      0.182      -0.617       0.117
Black          0.1313      0.221      0.595      0.552      -0.301       0.564
Tertiary      -0.2302      0.190     -1.213      0.225      -0.602       0.142
==============================================================================
"""

In [576]:
a = smf.logit(formula = "Salary_Increased ~ Province_Free_State + Province_Gauteng + Province_KwaZulu_Natal + Province_Limpopo + Province_Mpumalanga + Province_North_West + Province_Northern_Cape", data=df_dummies).fit()
a.summary()

Optimization terminated successfully.
         Current function value: 0.431902
         Iterations 6

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:       Salary_Increased   No. Observations:                  668
Model:                          Logit   Df Residuals:                      660
Method:                           MLE   Df Model:                            7
Date:                Sat, 19 Jun 2021   Pseudo R-squ.:                 0.01833
Time:                        19:18:48   Log-Likelihood:                -288.51
converged:                       True   LL-Null:                       -293.90
Covariance Type:            nonrobust   LLR p-value:                    0.1487
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -2.0711      0.274     -7.559      0.000      -2.608      -1.534
Province_Free_State        0.7101      0.448      1.585      0.113      -0.168       1.588
Province_Gauteng           0.5512      0.344      1.601      0.109      -0.124       1.226
Province_KwaZulu_Natal     0.8026      0.350      2.293      0.022       0.117       1.489
Province_Limpopo          -0.1802      0.593     -0.304      0.761      -1.342       0.982
Province_Mpumalanga        0.5512      0.403      1.369      0.171      -0.238       1.340
Province_North_West        0.1615      0.602      0.268      0.788      -1.018       1.341
Province_Northern_Cape    -0.2315      0.543     -0.426      0.670      -1.296       0.833
==========================================================================================
"""

In [579]:
a = smf.logit(formula = "Salary_Increased ~ Black + Tertiary + Province_KwaZulu_Natal", data=df_dummies).fit()
a.summary()

Optimization terminated successfully.
         Current function value: 0.428843
         Iterations 6

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:       Salary_Increased   No. Observations:                  668
Model:                          Logit   Df Residuals:                      664
Method:                           MLE   Df Model:                            3
Date:                Sat, 19 Jun 2021   Pseudo R-squ.:                 0.02528
Time:                        19:19:23   Log-Likelihood:                -286.47
converged:                       True   LL-Null:                       -293.90
Covariance Type:            nonrobust   LLR p-value:                  0.001938
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -2.1680      0.299     -7.251      0.000      -2.754      -1.582
Black                      0.7555      0.301      2.514      0.012       0.167       1.345
Tertiary                  -0.3473      0.218     -1.591      0.112      -0.775       0.081
Province_KwaZulu_Natal     0.3296      0.255      1.295      0.195      -0.169       0.828
==========================================================================================
"""

# LINEAR

In [310]:
a = smf.ols(formula = "Pay_Diff ~ Province_Eastern_Cape + Province_Free_State + Province_Gauteng + Province_KwaZulu_Natal + Province_Limpopo + Province_Mpumalanga + Province_North_West + Province_Northern_Cape + Province_Western_Cape", data=df_dummies).fit()
a.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Pay_Diff   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     1.112
Date:                Sat, 19 Jun 2021   Prob (F-statistic):              0.353
Time:                        18:14:50   Log-Likelihood:                 456.14
No. Observations:                 668   AIC:                            -894.3
Df Residuals:                     659   BIC:                            -853.8
Df Model:                           8
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  0.3580      0.005     74.629      0.000       0.349       0.367
Province_Eastern_Cape      0.0533      0.015      3.659      0.000       0.025       0.082
Province_Free_State        0.0079      0.016      0.479      0.632      -0.024       0.040
Province_Gauteng           0.0410      0.010      4.088      0.000       0.021       0.061
Province_KwaZulu_Natal     0.0543      0.011      4.923      0.000       0.033       0.076
Province_Limpopo           0.0321      0.018      1.820      0.069      -0.003       0.067
Province_Mpumalanga        0.0528      0.013      3.957      0.000       0.027       0.079
Province_North_West        0.0172      0.020      0.843      0.399      -0.023       0.057
Province_Northern_Cape     0.0404      0.016      2.589      0.010       0.010       0.071
Province_Western_Cape      0.0590      0.014      4.215      0.000       0.032       0.087
==============================================================================
Omnibus:                      122.174   Durbin-Watson:                   1.870
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              979.437
Skew:                          -0.560   Prob(JB):                    2.08e-213
Kurtosis:                       8.826   Cond. No.                     4.25e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.24e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [123]:
firstFucker = smf.ols(formula = "Pay_Diff ~  Usual_Work_Craft_and_related_trades_workers + Usual_Work_Clerical_support_workers + Usual_Work_Plant_and_machine_operators_and_assemblers + Usual_Work_Professionals + Usual_Work_Service_and_sales_workers + Usual_Work_Technicians_and_associate_professionals -1 ", data=df_dummies).fit()
firstFucker.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:               Pay_Diff   R-squared (uncentered):                   0.035
Model:                            OLS   Adj. R-squared (uncentered):              0.026
Method:                 Least Squares   F-statistic:                              3.978
Date:                Sun, 20 Jun 2021   Prob (F-statistic):                    0.000641
Time:                        19:39:34   Log-Likelihood:                         -3196.1
No. Observations:                 668   AIC:                                      6404.
Df Residuals:                     662   BIC:                                      6431.
Df Model:                           6
Covariance Type:            nonrobust
=========================================================================================================================
                                                            coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------
Usual_Work_Craft_and_related_trades_workers              -3.8497      5.309     -0.725      0.469     -14.275       6.576
Usual_Work_Clerical_support_workers                      -8.4999      3.192     -2.663      0.008     -14.768      -2.232
Usual_Work_Plant_and_machine_operators_and_assemblers    -6.0620      4.335     -1.398      0.162     -14.574       2.450
Usual_Work_Professionals                                 -4.2612      2.522     -1.690      0.092      -9.213       0.690
Usual_Work_Service_and_sales_workers                     -1.4127      2.407     -0.587      0.557      -6.139       3.313
Usual_Work_Technicians_and_associate_professionals      -11.4156      3.427     -3.331      0.001     -18.145      -4.686
==============================================================================
Omnibus:                      125.810   Durbin-Watson:                   1.852
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              920.587
Skew:                          -0.619   Prob(JB):                    1.25e-200
Kurtosis:                       8.616   Cond. No.                         2.21
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [314]:
second = smf.ols(formula = "Pay_Diff ~ Male", data=df_dummies).fit()
second.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Pay_Diff   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     4.254
Date:                Sat, 19 Jun 2021   Prob (F-statistic):             0.0395
Time:                        18:15:02   Log-Likelihood:                 453.79
No. Observations:                 668   AIC:                            -903.6
Df Residuals:                     666   BIC:                            -894.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.3921      0.007     58.854      0.000       0.379       0.405
Male           0.0196      0.010      2.063      0.040       0.001       0.038
==============================================================================
Omnibus:                      123.923   Durbin-Watson:                   1.868
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              996.733
Skew:                          -0.572   Prob(JB):                    3.65e-217
Kurtosis:                       8.874   Cond. No.                         2.60
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [126]:
third = smf.ols(formula = "Pay_Diff ~ Usual_Work_Service_and_sales_workers", data=df_dummies).fit()
third.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Pay_Diff   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     3.678
Date:                Sun, 20 Jun 2021   Prob (F-statistic):             0.0556
Time:                        19:39:58   Log-Likelihood:                -3194.3
No. Observations:                 668   AIC:                             6393.
Df Residuals:                     666   BIC:                             6402.
Df Model:                           1
Covariance Type:            nonrobust
========================================================================================================
                                           coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                               -6.6053      1.266     -5.219      0.000      -9.091      -4.120
Usual_Work_Service_and_sales_workers     5.1926      2.707      1.918      0.056      -0.124      10.509
==============================================================================
Omnibus:                      130.829   Durbin-Watson:                   1.870
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              963.172
Skew:                          -0.653   Prob(JB):                    7.08e-210
Kurtosis:                       8.736   Cond. No.                         2.56
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [127]:
fourth = smf.ols(formula = "Pay_Diff ~ Youth -1ZZ", data=df_dummies).fit()
fourth.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Pay_Diff   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.1214
Date:                Sun, 20 Jun 2021   Prob (F-statistic):              0.728
Time:                        19:40:06   Log-Likelihood:                -3196.1
No. Observations:                 668   AIC:                             6396.
Df Residuals:                     666   BIC:                             6405.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -5.3813      1.151     -4.677      0.000      -7.641      -3.122
Youth         -1.8036      5.177     -0.348      0.728     -11.969       8.362
==============================================================================
Omnibus:                      128.856   Durbin-Watson:                   1.870
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1005.374
Skew:                          -0.619   Prob(JB):                    4.85e-219
Kurtosis:                       8.881   Cond. No.                         4.63
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [131]:
best = smf.ols(formula = "Pay_Diff ~ Male + Black + Usual_Work_Service_and_sales_workers", data=df_dummies).fit()
best.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Pay_Diff   R-squared:                       0.011
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     2.507
Date:                Sun, 20 Jun 2021   Prob (F-statistic):             0.0580
Time:                        19:40:37   Log-Likelihood:                -3192.4
No. Observations:                 668   AIC:                             6393.
Df Residuals:                     664   BIC:                             6411.
Df Model:                           3
Covariance Type:            nonrobust
========================================================================================================
                                           coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                               -9.3746      2.463     -3.806      0.000     -14.212      -4.538
Male                                     4.3142      2.243      1.923      0.055      -0.091       8.719
Black                                    1.0734      2.607      0.412      0.681      -4.045       6.192
Usual_Work_Service_and_sales_workers     4.5314      2.773      1.634      0.103      -0.913       9.976
==============================================================================
Omnibus:                      127.007   Durbin-Watson:                   1.870
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              955.655
Skew:                          -0.618   Prob(JB):                    3.03e-208
Kurtosis:                       8.728   Cond. No.                         4.31
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [134]:
best = smf.ols(formula = "Pay_Diff ~ Male + White ", data=df_dummies).fit()
best.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Pay_Diff   R-squared:                       0.011
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     3.846
Date:                Sun, 20 Jun 2021   Prob (F-statistic):             0.0218
Time:                        19:40:54   Log-Likelihood:                -3192.3
No. Observations:                 668   AIC:                             6391.
Df Residuals:                     665   BIC:                             6404.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -7.0585      1.607     -4.392      0.000     -10.214      -3.903
Male           4.7195      2.234      2.113      0.035       0.333       9.106
White         -6.5829      3.558     -1.850      0.065     -13.570       0.404
==============================================================================
Omnibus:                      124.620   Durbin-Watson:                   1.881
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              982.627
Skew:                          -0.584   Prob(JB):                    4.22e-214
Kurtosis:                       8.826   Cond. No.                         3.67
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""